### ISSUE TITLE
rename from aiosmf -> smf-py

### ISSUE THREAD

**Issue by senior7515** [smfrpc/smf-pyaio#19]
i renamed it to smf-py from aiosmf - so i'm sure we need docs updated / etc

**Comment by noahdesu** [comment]
the only issue with this is that it's fairly standard to use `aio` in the name of libraries that use asyncio compared to non-asyncio-based python libraries. though, i'm not sure it really matters to anyone.

**Comment by senior7515** [comment]
should we rename `smf-aiopy`  then? i'm open to suggestions.

**Comment by noahdesu** [comment]
i think that'd be more flexible in the future if someone decides to build a non-asyncio version. you can see some common naming schemes here https://github.com/aio-libs

**Comment by senior7515** [comment]
so when a user lands on the smfrpc root project, they should be quickly able to find the python version. That is one of the main goals. Second goal it should be the async io in the name. 

What do you propose for name tho?

**Comment by noahdesu** [comment]
`python-aiosmf` and `python-smf` are good in terms of following some naming conventions, though this isn't strict at all. if you want the `smf-` prefix then you can just make up something like `smf-pyaio`. i think this is a pretty minor thing.

**Comment by senior7515** [comment]
great, do you mind if we do `smf-pyaio` ?

**Comment by senior7515** [comment]
done
